name: Data Pipeline CI

on:
  push:
    branches: [ "main" ]  # Triggers automatically whenever you push code to main

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Spins up a clean virtual machine running Linux
    steps:
    - uses: actions/checkout@v3          # Copies your repo code onto the VM
    - uses: actions/setup-python@v4      # Installs Python 3.10 on the VM
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: pip install -r requirements.txt  # Installs Pandas, Pytest, Streamlit, etc.

    - name: Lint Code Quality (Flake8)
      run: flake8 . --count --select=E9,F63,F7,F82  # Scans for Python syntax errors

    - name: Run Unit Tests
      env:
        PYTHONPATH: .                      # Tells Python to treat root as an import path
      run: pytest tests/                   # Runs all automated unit tests in /tests
